export var EldCachedDataRecordTypes =
{
    ELD_CACHED_DATA_RECORD_NONE:0,
    ELD_CACHED_ENGINEOFF_RECORD:1,
    ELD_CACHED_ENGINEON_RECORD:2,
    ELD_CACHED_NOT_FOUND3:3,
    ELD_CACHED_PERIODIC_RECORD:4,
    ELD_CACHED_POWERON_RECORD:5,
    ELD_CACHED_UNKNOWN:6,
}