
/* LOGIN */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

/* SIGNUP */
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

/* USER */
export const GETUSER_SUCCESS = 'GETUSER_SUCCESS';
export const GETUSER_FAIL = 'GETUSER_FAIL';
export const SET_USER_TYPE = 'SET_USER_TYPE';
export const UPDATE_USER_STATE = 'UPDATE_USER_STATE';

/* SHIPMENTS */
export const GET_ALL_AVAILABLE_SHIPMENTS_REQUEST = 'GET_ALL_AVAILABLE_SHIPMENTS_REQUEST';
export const GET_ALL_AVAILABLE_SHIPMENTS_SUCCESS = 'GET_ALL_AVAILABLE_SHIPMENTS_SUCCESS';
export const GET_ALL_AVAILABLE_SHIPMENTS_FAIL = 'GET_ALL_AVAILABLE_SHIPMENTS_FAIL';
export const SELECT_SHIPMENT = 'SELECT_SHIPMENT';
export const ACCEPT_SHIPMENT_REQUEST = 'ACCEPT_SHIPMENT_REQUEST';
export const ACCEPT_SHIPMENT_SUCCESS = 'ACCEPT_SHIPMENT_SUCCESS';
export const ACCEPT_SHIPMENT_FAIL = 'ACCEPT_SHIPMENT_FAIL';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SEARCH_ALL_AVAILABLE_SHIPMENTS_SUCCESS = 'SEARCH_ALL_AVAILABLE_SHIPMENTS_SUCCESS';
export const ADD_SHIPMENT_FOR_ACCEPTANCE = 'ADD_SHIPMENT_FOR_ACCEPTANCE';
export const CLEAR_SHIPMENT = 'CLEAR_SHIPMENT';
export const CLEAR_SEARCH_QUERY = 'CLEAR_SEARCH_QUERY';
export const CLEAR_SELECTED = 'CLEAR_SELECTED';
export const GET_SHIPMENT_BY_ID = 'GET_SHIPMENT_BY_ID';
export const CLEAR_ASSIGNED_SHIPMENT = 'CLEAR_ASSIGNED_SHIPMENT';
export const CLEAR_ALL_QUERY = 'CLEAR_ALL_QUERY';

/* RESET PASSWORD */
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL';

/* Driver Shipment */

export const DRIVER_GET_LIVE_SHIPMENTS_REQUEST = 'DRIVER_GET_LIVE_SHIPMENTS_REQUEST';
export const DRIVER_GET_LIVE_SHIPMENTS_SUCCESS = 'DRIVER_GET_LIVE_SHIPMENTS_SUCCESS';
export const DRIVER_GET_LIVE_SHIPMENTS_FAIL = 'DRIVER_GET_LIVE_SHIPMENTS_FAIL';

export const DRIVER_GET_UPCOMING_SHIPMENTS_REQUEST = 'DRIVER_GET_UPCOMING_SHIPMENTS_REQUEST';
export const DRIVER_GET_UPCOMING_SHIPMENTS_SUCCESS = 'DRIVER_GET_UPCOMING_SHIPMENTS_SUCCESS';
export const DRIVER_GET_UPCOMING_SHIPMENTS_FAIL = 'DRIVER_GET_UPCOMING_SHIPMENTS_FAIL';

export const DRIVER_GET_PAST_SHIPMENTS_REQUEST = 'DRIVER_GET_PAST_SHIPMENTS_REQUEST';
export const DRIVER_GET_PAST_SHIPMENTS_SUCCESS = 'DRIVER_GET_PAST_SHIPMENTS_SUCCESS';
export const DRIVER_GET_PAST_SHIPMENTS_FAIL = 'DRIVER_GET_PAST_SHIPMENTS_FAIL';

export const DRIVER_GET_UPCOMING_SHIPMENTS_COUNT_SUCCESS = 'DRIVER_GET_UPCOMING_SHIPMENTS_COUNT_SUCCESS';
export const DRIVER_GET_UPCOMING_SHIPMENTS_COUNT_FAIL = 'DRIVER_GET_UPCOMING_SHIPMENTS_COUNT_FAIL';


export const GET_ACTIVITY_LOG_REQUEST = 'GET_ACTIVITY_LOG_REQUEST';
export const GET_ACTIVITY_LOG_SUCCESS = 'GET_ACTIVITY_LOG_SUCCESS';
export const GET_ACTIVITY_LOG_FAIL = 'GET_ACTIVITY_LOG_FAIL';
export const GET_ACTIVITY_LOG_DAY_SUCCESS = 'GET_ACTIVITY_LOG_DAY_SUCCESS';
