export const UPDATE_USER = 'UPDATE_USER';

// Pick up

export const SEND_CARRIER_REQUEST = 'SEND_CARRIER_REQUEST';
export const SEND_REQUEST_FAIL = 'SEND_REQUEST_FAIL';
export const SEND_REQUEST_SUCCESS = 'SEND_REQUEST_SUCCESS';


export const UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT';
